mygametracker/collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:user>/', views.CreateCollection.as_view(), name='main'),
    path('<str:user>/delete/<int:collection_id>', views.delete_collection, name='delete'),
    path('<str:user>/edit/<int:collection_id>', views.update_collection, name='edit'),
    path('<str:user>/<int:collection_id>', views.collection_detail, name='collection_detail'),
]

mygametracker/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='main'),
    path('create/', views.create_forum, name='create_forum'),
    path('<int:forum_id>/', views.forum_details, name='forum_details'),
    path('<int:forum_id>/update/', views.update_forum, name='update_forum'),
    path('forums/<int:forum_id>/create_post/', views.create_post, name='create_post'),
    path('update_post/<int:post_id>/', views.UpdatePostView.as_view(), name='update_post'),
]

mygametracker/game/urls.py
from django.urls import path
from .views import home, add_new_game, top_credits, games_list

app_name = 'game'

urlpatterns = [
    path('', home, name='home'),
    path('add_new_game/', add_new_game, name='add_new_game'),
    path('top_credits/', top_credits, name='top_credits'),
    path('games_list/', games_list, name='games_list'),
]

mygametracker/mygametracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('collections/', include('collection.urls')),
    path('forum/', include('forum.urls')),
    path('', include('game.urls')),
    path('stats/', include('stats.urls')),
]

mygametracker/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.UserSignup.as_view(), name='signup'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('friends/', views.friends, name='friends'),
    path('add_friend/', views.add_friend, name='add_friend'),
]

mygametracker/game/models.py
from django.db import models
from django.urls import reverse


# from stats.models import Platform


# Create your models here.
class Developer(models.Model):
    developer_id = models.AutoField(primary_key=True)
    developer = models.CharField(max_length=64)

    def __str__(self):
        return self


class Publisher(models.Model):
    publisher_id = models.AutoField(primary_key=True)
    publisher = models.CharField(max_length=64)

    def __str__(self):
        return self

class Genre(models.Model):
    genre_id = models.AutoField(primary_key=True)
    genre = models.CharField(max_length=64)

    def __str__(self):
        return self


class Game(models.Model):
    game_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    description = models.TextField()
    release_date = models.DateField()
    platforms = models.ManyToManyField("stats.Platform")
    publishers = models.ManyToManyField(Publisher)
    developers = models.ManyToManyField(Developer)
    genres = models.ManyToManyField(Genre)
    rating = models.FloatField()
    image = models.URLField(default='https://example.com/default-image.jpg')  # Add this line for the image URL

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('game_detail', args=[str(self.game_id)])

mygametracker/game/forms.py
from django.forms import ModelForm, DateInput
from django import forms
from .models import Game


class AddNewGameForm(ModelForm):
    title = forms.CharField(widget=forms.TextInput({
        'class': 'form-control',
        'placeholder': 'Title'
    }))

    genre = forms.CharField(widget=forms.TextInput({
        'class': 'form-control',
        'placeholder': 'Genre'
    }))

    description = forms.CharField(widget=forms.Textarea({
        'class': 'form-control',
        'placeholder': 'Description'
    }))

    release_date = forms.DateField(widget=DateInput({
        'type': 'date',
        'class': 'form-control'
    }))

    image = forms.CharField(widget=forms.TextInput({
        'class': 'form-control',
        'placeholder': 'Image (Optional)'
    }), required=False)

    class Meta:
        model = Game
        fields = ['title', 'genre', 'description', 'release_date', 'image']

mygametracker/game/views.py
from django.db import IntegrityError, OperationalError
from django.shortcuts import render, redirect
from django.db import connection
from .models import Game


class GameExistsError(Exception):
    pass


def home(request):
    # Retrieve 5 random games using a stored procedure
    with connection.cursor() as cursor:
        cursor.callproc('GetRandomGames', [5])
        games_for_you = [dict(zip([col[0] for col in cursor.description], row)) for row in cursor.fetchall()]

    # Retrieve 5 games ordered by rating using a stored procedure
    with connection.cursor() as cursor:
        cursor.callproc('GetTopRatedGames', [5])
        games_for_you2 = [dict(zip([col[0] for col in cursor.description], row)) for row in cursor.fetchall()]

    return render(request, 'home.html', {'games_for_you': games_for_you, 'games_for_you2': games_for_you2})

def add_new_game(request):
    success_message = None
    error_message = None
    info_message = None

    if request.method == 'POST':
        title = request.POST.get('title')
        genre = request.POST.get('genre')
        description = request.POST.get('description')
        image = request.POST.get('image')
        release_date = request.POST.get('release_date')
        username_credits = request.session.get('curr_user')

        # Assuming you have a user_id available in your session
        if len(image) is 0:
            image = 'http://tinyurl.com/yajp3tyy'
        if username_credits is not None:
            try:
                # Call the stored procedure
                with connection.cursor() as cursor:
                    cursor.callproc('AddNewGame', [title, description, release_date, genre, username_credits, image])

                # Set success message
                success_message = 'Success: New game added.'


            except IntegrityError as e:

                # Check if it's a title already exists error

                if "Error: Title already exists" in str(e):

                    error_message = 'Error: The title already exists. Please choose a different title.'

                else:



                    error_message = f"Error: {str(e)}"


            except OperationalError as e:

                # Handle the specific OperationalError

                error_message = f"Game already exists!"

            except GameExistsError as e:

                error_message = str(e)

        else:
            # Handle the case where user_id is not available
            error_message = "Error: User not logged in"

    return render(request, 'add_new_game.html', {'success_message': success_message, 'error_message': error_message, 'info_message': info_message})

def top_credits(request):
    top_credits_list = []

    with connection.cursor() as cursor:
        cursor.callproc('GetTopCredits', [10])
        top_credits_list = [dict(zip([col[0] for col in cursor.description], row)) for row in cursor.fetchall()]

    return render(request, 'top_credits.html', {'top_credits_list': top_credits_list})

def games_list(request):
    with connection.cursor() as cursor:
        cursor.callproc('GetAllGames', [])
        games_list = [dict(zip([col[0] for col in cursor.description], row)) for row in cursor.fetchall()]

    # Order the games alphabetically by title
    games_list = sorted(games_list, key=lambda x: x['title'])

    return render(request, 'games_list.html', {'games_list': games_list})

mygametracker/game/templates/add_new_game.html
{% extends 'base.html' %}
{% block title %}Add New Game{% endblock %}
{% block content %}

{% load static %}

<div class="container mt-4">

  {% if request.session.curr_user != '' %}
    <h1 class="mb-4">Add New Game</h1>

    {% if success_message %}
      <div class="alert alert-success" role="alert">
        {{ success_message }}
      </div>
    {% endif %}

    {% if error_message %}
      <div class="alert alert-danger" role="alert">
        {{ error_message }}
      </div>
    {% endif %}

    {% if info_message %}
      <div class="alert alert-info" role="alert">
        {{ info_message }}
      </div>
    {% endif %}

    <!-- Add your form here -->
    <form method="post" action="{% url 'game:add_new_game' %}">
      {% csrf_token %}

      <!-- Title -->
      <div class="mb-3">
        <label for="title" class="form-label">Title:</label>
        <input type="text" class="form-control" id="title" name="title" required>
      </div>

      <!-- Genre -->
      <div class="mb-3">
        <label for="genre" class="form-label">Genre:</label>
        <input type="text" class="form-control" id="genre" name="genre" required>
      </div>

      <!-- Description -->
      <div class="mb-3">
        <label for="description" class="form-label">Description:</label>
        <textarea class="form-control" id="description" name="description" rows="4" required></textarea>
      </div>
      <!-- Image URL -->
      <div class="mb-3">
        <label for="image" class="form-label">Image URL(optional):</label>
        <input type="text" class="form-control" id="image" name="image">
      </div>

      <!-- Release Date -->
      <div class="mb-3">
        <label for="release_date" class="form-label">Release Date:</label>
        <input type="date" class="form-control" id="release_date" name="release_date" required>
      </div>

      <button type="submit" class="btn btn-primary">Submit</button>
    </form>

  {% else %}
    <div class="alert alert-dismissible fade show border border-light">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <strong>Info!</strong> You are currently not logged in.
    </div>
    <h1 class="mb-4">Welcome to MyGameTracker!</h1>
  {% endif %}

</div>

{% endblock %}

mygametracker/game/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MyGameTracker - {% block title %}Base{% endblock %}</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <!-- Latest compiled and minified CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Latest compiled JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body class="bg-dark">
        {% include 'navbar.html' %}
        <div class="container-fluid p-5 mt-5 bg-dark text-white">
<!--            <br/>-->
<!--            {% if messages %}-->
<!--                {% for message in messages %}-->
<!--                <div class="alert alert-warning alert-dismissible fade show" role="alert">-->
<!--                    {{ message }}-->
<!--                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--                </div>-->
<!--                {% endfor %}-->
<!--            {% endif %}-->
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

mygametracker/game/templates/games_list.html
{% extends 'base.html' %}
{% block title %}Games List{% endblock %}
{% block content %}

<div class="container mt-4">

  <h1 class="mb-4">Games</h1>

  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for game in games_list %}
      <div class="col">
        <div class="card h-100 bg-secondary text-light">
          <img src="{{ game.image }}" class="card-img-top" alt="{{ game.title }}">
          <div class="card-body">
            <h5 class="card-title">{{ game.title }}</h5>
            <p class="card-text">{{ game.description }}</p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>Genres:</strong> {{ game.genres }}</li>
            <li class="list-group-item"><strong>Rating:</strong> {{ game.rating }}/10</li>
            <li class="list-group-item"><strong>Release Date:</strong> {{ game.release_date }}</li>
          </ul>
        </div>
      </div>
    {% endfor %}
  </div>

</div>

{% endblock %}

mygametracker/game/templates/home.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}

{% load static %}

<div class="container mt-4">

  {% if request.session.curr_user != '' %}

    <h1 class="mb-4">Welcome to MyGameTracker, {{ request.session.curr_user }}!</h1>
    <br>
    <br>
    <!-- Card -->
    <div class="modal fade" id="promoModal" tabindex="-1" aria-labelledby="promoModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="promoModalLabel">Promo Form</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <form method="post" action="{% url 'game:add_new_game' %}">
              {% csrf_token %}
              <!-- Title -->
              <div class="mb-3">
                <label for="title" class="form-label">Title:</label>
                <input type="text" class="form-control" id="title" name="title" required>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <br>
    <br>
    <!-- Set1 -->
    <h3 class="mb-3">Games For You:</h3>
    <div id="gameCarousel1" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for game in games_for_you %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="row">
              <div class="col-md-6">
                <div class="carousel-caption text-start">
                  <h5>{{ game.title }}</h5>
                  <p>Rating: {{ game.rating }}/10</p>
                </div>
              </div>
              <div class="col-md-6">
                <img src="{{ game.image }}" class="d-block mx-auto img-fluid" alt="{{ game.title }}">
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#gameCarousel1" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#gameCarousel1" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  <br>
  <br>
  <br>
   <!-- Set2 -->
    <h3 class="mb-3">Top Rated Games:</h3>
    <div id="gameCarousel2" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        {% for game in games_for_you2 %}
          <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="row">
              <div class="col-md-6">
                <div class="carousel-caption text-start">
                  <h5>{{ game.title }}</h5>
                  <p>Rating: {{ game.rating }}/10</p>
                </div>
              </div>
              <div class="col-md-6">
                <img src="{{ game.image }}" class="d-block mx-auto img-fluid" alt="{{ game.title }}">
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#gameCarousel2" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#gameCarousel2" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

  {% else %}

  <div class="alert alert-dismissible fade show border border-light">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <strong>Info!</strong> You are currently not logged in.
  </div>
  <h1 class="mb-4">Welcome to MyGameTracker!</h1>

  {% endif %}

</div>

{% endblock %}

mygametracker/game/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'game:home' %}"><b>MyGameTracker</b></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.session.curr_user != '' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'game:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'stats:search' %}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forum:main' %}">Forum</a>
        </li>

        <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
        Games
    </a>
    <div class="dropdown-menu dropdown-menu-dark bg-dark border border-secondary">
        <a class="dropdown-item" href="{% url 'game:games_list' %}">Games</a>
        <a class="dropdown-item" href="{% url 'game:top_credits' %}">Top Users</a>
            <div class="dropdown-divider bg-secondary"></div>
        <a class="dropdown-item" href="{% url 'game:add_new_game' %}">Add New Game</a>
    </div>
</li>

        <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-dark bg-dark border border-secondary">
            <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'user:friends' %}">Friends</a>
            <div class="dropdown-divider bg-secondary"></div>
            <a class="dropdown-item" href="{% url 'collection:main' user=request.session.curr_user %}">Collections</a>
            <a class="dropdown-item" href="{% url 'user:logout' %}">Log Out</a>
          </div>
        </li>



        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'stats:search' %}">Search</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'forum:main' %}">Forums</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-dark bg-dark border border-secondary">
            <a class="dropdown-item" href="{% url 'user:signup' %}">Sign Up</a>
            <div class="dropdown-divider bg-secondary"></div>
            <a class="dropdown-item" href="{% url 'user:login' %}">Log In</a>
          </div>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>

mygametracker/game/templates/top_credits.html
{% extends 'base.html' %}
{% block title %}Top Credits{% endblock %}
{% block content %}

<div class="container mt-4">

  <h1 class="mb-4">Top Users</h1>

  <div class="table-responsive">
    <table class="table table-bordered table-striped table-dark">
      <thead>
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Name</th>
          <th scope="col">Games Added</th>
        </tr>
      </thead>
      <tbody>
        {% for user in top_credits_list %}
          <tr class="{% if forloop.counter == 1 %}table-warning{% elif forloop.counter == 2 %}table-secondary{% elif forloop.counter == 3 %}table-info{% endif %}">
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ user.username }}</td>
            <td>{{ user.total_credits }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>

{% endblock %}

mygametracker/game/templates/trash.html
<form class="d-flex">
      <input class="form-control me-2" type="text" placeholder="Search">
      <button class="btn text-light" type="button">Search</button>
</form>


<button type="button" class="btn btn-outline-primary d-flex align-middle py-2 mx-1"
        style="z-index:3; position:relative;"
        data-bs-toggle="modal" data-bs-target="#deleteModal">
    <span class="material-symbols-outlined">Delete</span>
</button>
<button type="button" class="btn btn-primary d-flex align-middle py-2 mx-1"
        style="z-index:3; position:relative;"
        data-bs-toggle="modal" data-bs-target="#renameModal">
    <span class="material-symbols-outlined">Edit</span>
</button>