mygametracker/collection/urls.py
from django.urls import path
from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.index, name='index'),
    path('<str:user>/', views.CreateCollection.as_view(), name='main'),
    path('<str:user>/delete/<int:collection_id>', views.delete_collection, name='delete'),
    path('<str:user>/edit/<int:collection_id>', views.update_collection, name='edit'),
    path('<str:user>/<int:collection_id>', views.collection_detail, name='collection_detail'),
]

mygametracker/game/urls.py
from django.urls import path
from .views import home, add_new_game, top_credits, games_list

app_name = 'game'

urlpatterns = [
    path('', home, name='home'),
    path('add_new_game/', add_new_game, name='add_new_game'),
    path('top_credits/', top_credits, name='top_credits'),
    path('games_list/', games_list, name='games_list'),
]

mygametracker/mygametracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('collections/', include('collection.urls')),
    path('forum/', include('forum.urls')),
    path('', include('game.urls')),
    path('stats/', include('stats.urls')),
]

mygametracker/collection/models.py
from django.db import models
from user.models import User
from game.models import Game


class Collection(models.Model):
    collection_id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=256)
    date_modified = models.DateTimeField(auto_now=True, editable=False)
    is_private = models.BooleanField(default=False)
    types = (
        (0, "Normal"),
        (1, "Favorite"),
        (2, "Owned"),
        (3, "Playing"),
        (4, "Completed"),
    )
    type = models.IntegerField(choices=types, default=0)
    game_collection = models.ManyToManyField(Game)

    def __str__(self):
        return self.name

mygametracker/collection/forms.py
from django import forms
from .models import Collection


class CollectionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""  # Removes : as label suffix

    name = forms.CharField(label='', widget=forms.TextInput({
        'class': 'form-control mt-4',
        'placeholder': 'Collection Name'
    }))
    description = forms.CharField(label='', widget=forms.Textarea({
        'class': 'form-control mt-2',
        'rows': '3',
        'placeholder': 'Description'
    }))
    is_private = forms.BooleanField(label='Set as Private', required=False, widget=forms.CheckboxInput({
        'class': 'form-check-input',
        'style': 'float: left; margin-right: 10px; margin-top: 4px;'
    }))

    class Meta:
        model = Collection
        fields = ['name', 'description', 'is_private']

mygametracker/collection/views.py
from django.db import connection
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Collection
from .forms import CollectionForm
from user.models import User
from stats.models import UserGamePlatform


def index(request):
    return render(request, 'user_collections.html', {'user': ''})


def collection_detail(request, user, collection_id):
    user_id = User.objects.get(username=user).user_id
    collection = get_object_or_404(Collection, pk=collection_id, user_id=user_id)
    games = collection.game_collection.all()
    game_details = UserGamePlatform.objects.filter(user_id=user_id, game_id__in=games).distinct()
    return render(request, 'collection_detail.html', {'collection': collection, 'user': user, 'games': games, 'game_details': game_details})


def delete_collection(request, user, collection_id):
    user_object = User.objects.get(username=request.session['curr_user'])
    collections = Collection.objects.filter(user_id=user_object.user_id)
    form = CollectionForm()
    collection = get_object_or_404(Collection, pk=collection_id)
    if user_object == collection.user_id:
        collection.delete()
        messages.success(request, 'Collection deleted successfully.')
    else:
        messages.error(request, 'You do not have permission to delete this collection.')
    return render(request, 'user_collections.html', {'collections': collections, 'user': user, 'form': form})


def update_collection(request, user, collection_id):
    user_id = User.objects.get(username=user).user_id
    collections = Collection.objects.filter(user_id=user_id)
    form = CollectionForm()
    collection = get_object_or_404(Collection, pk=collection_id, user_id=user_id)
    if request.method == 'POST':
        collection.name = request.POST.get('txtCollectionName')
        collection.description = request.POST.get('txtDescription')
        if request.POST.get('cbPrivate') == 'on':
            collection.is_private = 1
        else:
            collection.is_private = 0
        collection.save()
        messages.success(request, 'Collection updated successfully.')
    return render(request, 'user_collections.html', {'collections': collections, 'user': user, 'form': form})


def execute_stored_procedure(user_id):
    with connection.cursor() as cursor:
        cursor.callproc('GenerateCompletedGamesCollection', [user_id])
        cursor.callproc('GeneratePlayedGamesCollection', [user_id])
        cursor.callproc('GenerateOwnedGamesCollection', [user_id])
        connection.commit()


class CreateCollection(View):
    template = 'user_collections.html'

    def get(self, request, user):
        user_id = User.objects.get(username=user).user_id
        execute_stored_procedure(user_id)
        collections = Collection.objects.filter(user_id=user_id)
        form = CollectionForm()
        return render(request, 'user_collections.html', {'collections': collections, 'user': user, 'form': form})

    def post(self, request, user):
        user_id = User.objects.get(username=user).user_id
        collections = Collection.objects.filter(user_id=user_id)
        form = CollectionForm(request.POST)
        if form.is_valid():
            if not Collection.objects.filter(name=form.cleaned_data['name'], user_id=user_id).exists():
                collection = form.save(commit=False)
                collection.user_id = User.objects.get(username=user)
                collection.save()
                messages.success(request, 'Collection added successfully.')
                return render(request, self.template, {'collections': collections, 'user': user, 'form': form})
            messages.error(request, 'A collection with this name already exists.')
        return render(request, self.template, {'collections': collections, 'user': user, 'form': form})

mygametracker/collection/templates/collection_detail.html
{% extends 'base.html' %}
{% block title %}{{ collection.name }} (Collection){% endblock %}
{% block content %}

{% if request.session.curr_user != '' %}

<h1><a class="text-light" href="{% url 'collection:main' user=user %}">Collections</a> > {{ collection.name }}</h1>
<div class="card bg-dark text-light border-light mt-4">
    <div class="card-body p-0">
        <table class="table table-dark table-hover table-borderless table-responsive my-1">
            <thead class="border-bottom">
            <tr>
                <th></th>
                <th>Game</th>
                <th>Status</th>
                <th>Score</th>
                <th>Review</th>
            </tr>
            </thead>
            <tbody>
            {% if games.count == 0 %}
            <tr><td class="text-center" colspan="5">No Games Found in Collection</td></tr>
            {% else %}
            {% for game in games %}
            <tr class="position-relative align-middle">
                <td scope="row"><a class="stretched-link" href=""></a></td>
                <td class="fs-5">{{ game.title }}</td>
                {% for detail in game_details %}
                {% if detail.game_id == game %}
                <td>{{ detail.status }}</td>
                <td>{{ detail.score }}</td>
                <td>{{ detail.review }}</td>
                {% endif %}
                {% endfor %}
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>


{% else %}

<div class="alert alert-dismissible fade show border border-light">
    <button class="btn-close" data-bs-dismiss="alert" type="button"></button>
    <strong>Info!</strong> You are currently not logged in.
</div>
<h1>Collections</h1>
<div class="card bg-dark text-light border-light mt-3">
    <div class="card-body">This page should contain the list of collections that the user have.</div>
</div>

{% endif %}

{% endblock %}


<!DOCTYPE html>
<html>
<head>
    <title>{{ collection.name }}</title>
</head>
<body>
    <h1>{{ collection.name }}</h1>
    <h2>Games in Collection:</h2>
    {% for game in collection.game_collection.all %}
        <p>{{ game.title }}</p>
    {% endfor %}
</body>
</html>

mygametracker/collection/templates/user_collections.html
{% extends 'base.html' %}
{% block title %}Collections{% endblock %}
{% block content %}

{% if user != '' %}

{% if messages %}
{% for message in messages %}
<div class="alert alert-dismissible fade show border border-light">
    <button class="btn-close" data-bs-dismiss="alert" type="button"></button>
    {{ message }}
</div>
{% endfor %}
{% endif %}

<div class="clearfix">
    <span class="float-start"><h1>Collections</h1></span>
    <span class="float-end">
        {% if request.session.curr_user == user %}
        <button type="button" class="btn btn-primary d-flex align-middle py-2" style="z-index:3; position:relative;"
                data-bs-toggle="modal" data-bs-target="#addModal">
            <span class="material-symbols-outlined">add</span>
        </button>
        {% endif %}
    </span>
</div>
<div class="card bg-dark text-light border-light mt-3">
    <div class="card-body p-0">
        <table class="table table-dark table-hover table-borderless table-responsive my-1">
            <thead class="border-bottom">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Description</th>
                <th>Last Modified</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for collection in collections %}
            {% if collection.is_private == 0 or request.session.curr_user == user %}
            <tr class="position-relative align-middle">
                <td scope="row">
                    <a class="stretched-link"
                       href="{% url 'collection:collection_detail' collection_id=collection.collection_id user=user %}"></a>
                </td>
                <td class="fs-5">{{ collection.name }}
                    {% if request.session.curr_user == user %}
                    {% if collection.type == 0 %}
                    {% if collection.is_private == 0 %}
                    <span class="badge bg-primary">Public</span>
                    {% else %}
                    <span class="badge bg-danger">Private</span>
                    {% endif %}
                    {% else %}
                    <span class="badge bg-secondary">Auto</span>
                    {% endif %}
                    {% endif %}
                </td>
                <td>{% if collection.type == 0 %}{{ collection.description }}{% else %}<i class="text-secondary">Generated based on user-provided game status.</i>{% endif %}
                </td>
                <td>{{ collection.date_modified }}</td>
                {% if request.session.curr_user == user and collection.type == 0 %}
                <td class="d-flex flex-row-reverse">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary d-flex align-middle py-2"
                                style="z-index:3; position:relative;"
                                data-bs-toggle="modal" data-bs-target="#editModal{{collection.collection_id}}">
                            <span class="material-symbols-outlined">edit</span>
                        </button>
                        <button type="button" class="btn btn-danger d-flex align-middle py-2"
                                style="z-index:3; position:relative;"
                                data-bs-toggle="modal" data-bs-target="#deleteModal{{collection.collection_id}}">
                            <span class="material-symbols-outlined">delete</span>
                        </button>
                    </div>
                </td>
                <!-- Edit Collection Modal -->
                <form method="post"
                      action="{% url 'collection:edit' collection_id=collection.collection_id user=user %}">
                    {% csrf_token %}
                    <div class="modal fade" id="editModal{{collection.collection_id}}">
                        <div class="modal-dialog">
                            <div class="modal-content bg-dark">
                                <div class="modal-header">
                                    <h4>Edit Collection</h4>
                                    <button type="button" class="btn-close btn-close-white"
                                            data-bs-dismiss="modal"></button>
                                </div>
                                <div class="modal-body">
                                    <div class="my-3">
                                        <input type="text" id="txtCollectionName" name="txtCollectionName"
                                               class="form-control" placeholder="Collection Name"
                                               value="{{ collection.name }}" required>
                                        <div class="invalid-feedback">Please fill out this field.</div>
                                    </div>
                                    <div>
                                    <textarea name="txtDescription" cols="40" rows="3" class="form-control mt-2"
                                              placeholder="Description" required="" id="txtDescription">{{ collection.description }}</textarea>
                                    </div>
                                    <div class="form-check my-3">
                                        <input type="checkbox" id="cbPrivate" name="cbPrivate" class="form-check-input"
                                               {% if collection.is_private %}checked{% endif %}>
                                        <label for="cbPrivate" class="form-check-label">Set as Private</label>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <input type="submit" class="btn btn-primary" name="btnRegister" value="Confirm">
                                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

                <!-- Delete Collection Modal -->
                <div class="modal fade" id="deleteModal{{collection.collection_id}}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h4>Delete Collection</h4>
                                <button type="button" class="btn-close btn-close-white"
                                        data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                Are you sure that you want to delete "{{ collection.name }}"?
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'collection:delete' collection_id=collection.collection_id user=user %}"
                                   class="btn btn-danger">Confirm</a>
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cancel
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                {% else %}
                <td></td>
                {% endif %}
            </tr>
            {% endif %}
            {% endfor %}

            <!-- Add Collection Modal -->
            <form method="post" action="{% url 'collection:main' user=user %}">
                {% csrf_token %}
                <div class="modal fade" id="addModal">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h4>Create New Collection</h4>
                                <button type="button" class="btn-close btn-close-white"
                                        data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                {{ form.as_p }}
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-primary" name="btnRegister" value="Submit">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            </tbody>
        </table>
    </div>
</div>

{% else %}

<div class="alert alert-dismissible fade show border border-light">
    <button class="btn-close" data-bs-dismiss="alert" type="button"></button>
    <strong>Warning!</strong> No collection selected.
</div>
<h1>Collections</h1>
<div class="card bg-dark text-light border-light mt-3">
    <div class="card-body">This page should contain the list of collections that the user have.</div>
</div>

{% endif %}

{% endblock %}