mygametracker/game/urls.py
from django.urls import path
from .views import home, add_new_game, top_credits, games_list

app_name = 'game'

urlpatterns = [
    path('', home, name='home'),
    path('add_new_game/', add_new_game, name='add_new_game'),
    path('top_credits/', top_credits, name='top_credits'),
    path('games_list/', games_list, name='games_list'),
]

mygametracker/mygametracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('collections/', include('collection.urls')),
    path('forum/', include('forum.urls')),
    path('', include('game.urls')),
    path('stats/', include('stats.urls')),
]

mygametracker/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('signup/', views.UserSignup.as_view(), name='signup'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('delete_profile/', views.delete_profile, name='delete_profile'),
    path('friends/', views.friends, name='friends'),
    path('add_friend/', views.add_friend, name='add_friend'),
]

mygametracker/user/models.py
from django.db import models


class User(models.Model):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=64)
    join_date = models.DateTimeField(auto_now_add=True)
    email = models.EmailField(max_length=128)
    password = models.CharField(max_length=64)
    bio = models.TextField()
    genders = (
        ("M", "Male"),
        ("F", "Female")
    )
    gender = models.CharField(max_length=1, choices=genders)

    def __str__(self):
        return self

    def update_profile(self, new_username,new_password ,new_email, new_bio, new_gender):
        self.username = new_username
        self.password = new_password
        self.email = new_email
        self.bio = new_bio
        self.gender = new_gender
        self.save()


class UserFriend(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_friends')
    friend = models.ForeignKey(User, on_delete=models.CASCADE, related_name='friend_of')
    friend_username = models.CharField(max_length=255)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.friend_username)

mygametracker/user/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db import connection, IntegrityError
from django.http import HttpResponse
from .form import SignupForm, LoginForm, UserProfileUpdateForm
from .models import User, UserFriend
from django.shortcuts import render, redirect
from django.views import View


def index(request):
    return HttpResponse("This is the Home Page.")


def logout(request):
    request.session['curr_user'] = ''
    return redirect('user:login')


def dashboard(request):
    user = User.objects.all()
    return render(request, 'dashboard.html', {'users': user})


def profile(request):
    current_username = request.session.get('curr_user')

    if current_username:
        try:
            user = User.objects.get(username=current_username)
        except User.DoesNotExist:
            return HttpResponse("User does not exist")

        if request.method == 'POST':
            form = UserProfileUpdateForm(request.POST)

            if form.is_valid():
                new_username = form.cleaned_data['new_username']
                new_password = form.cleaned_data['new_password']
                new_email = form.cleaned_data['new_email']
                new_bio = form.cleaned_data['new_bio']
                new_gender = form.cleaned_data['new_gender']

                user.username = new_username
                user.password = new_password
                user.email = new_email
                user.bio = new_bio
                user.gender = new_gender
                user.save()

                return redirect('user:login')
        else:
            form = UserProfileUpdateForm()

        return render(request, 'profile.html', {'user': user, 'form': form})
    else:
        return HttpResponse("User not authenticated")


def delete_profile(request):
    if request.method == 'POST':
        current_username = request.session.get('curr_user')

        if current_username:
            try:
                with connection.cursor() as cursor:
                    cursor.callproc('DeleteUserProfile', [current_username])

                request.session.clear()

                return redirect('user:logout')
            except IntegrityError as e:
                return HttpResponse("Error deleting user profile")
        else:
            return HttpResponse("Current user not found")
    else:
        return HttpResponse("Invalid request method")


def friends(request):
    user_object = User.objects.get(username=request.session['curr_user'])
    current_user_id = user_object.user_id

    friends = UserFriend.objects.filter(user_id=user_object.user_id)

    if request.method == 'POST':
        friend_username = request.POST.get('friend_username')

        with connection.cursor() as cursor:
            cursor.callproc('DeleteUserFriend', [current_user_id, friend_username])

    return render(request, 'friends.html', {'friends': friends})


def add_friend(request):
    if request.method == 'POST':
        friend_username = request.POST.get('friend_username')

        try:
            friend_object = User.objects.get(username=friend_username)
            friend_user_id = friend_object.user_id

            user_object = User.objects.get(username=request.session['curr_user'])
            current_user_id = user_object.user_id

            if not UserFriend.objects.filter(user_id=current_user_id, friend_id=friend_user_id).exists():
                with connection.cursor() as cursor:
                    cursor.callproc('AddUserFriend', [current_user_id, friend_user_id, friend_username])

        except ObjectDoesNotExist:
            return redirect('user:friends')

    return redirect('user:friends')


class UserSignup(View):
    template = 'signup.html'

    def get(self, request):
        user = SignupForm()
        return render(request, self.template, {'form': user})

    def post(self, request):
        user = SignupForm()
        error = False

        if request.method == 'POST':
            user = SignupForm(request.POST)

            if user.is_valid():
                username = request.POST.get('username')
                email = request.POST.get('email')
                password = request.POST.get('password')
                gender = request.POST.get('gender')

                if len(User.objects.filter(username=username, email=email, password=password, gender=gender)) == 0:
                    try:
                        with connection.cursor() as cursor:
                            cursor.callproc('CreateUserProfile', [username, email, password, gender])
                    except IntegrityError as e:
                        error = True
                        return render(request, self.template, {'form': user, 'response': error})

                    return redirect('user:login')

        return render(request, self.template, {'form': user, 'response': error})


class UserLogin(View):
    template = 'login.html'

    def get(self, request):
        login = LoginForm()
        return render(request, self.template, {'form': login})

    def post(self, request):
        login = LoginForm()
        username = request.POST.get("username")
        password = request.POST.get("password")
        error = False
        try:
            user = User.objects.get(username=username, password=password)
            request.session['curr_user'] = username
            print("Login successful")
            return render(request, 'home.html')
        except User.DoesNotExist:
            error = True
            print("Login failed")
            return render(request, self.template, {'form': login, "response": error})

mygametracker/user/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>MyGameTracker - {% block title %}Base{% endblock %}</title>
        <!-- Latest compiled and minified CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Latest compiled JavaScript -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </head>
    <body>
        {% include 'navbar.html' %}
        <div class="container">
<!--            <br/>-->
<!--            {% if messages %}-->
<!--                {% for message in messages %}-->
<!--                <div class="alert alert-warning alert-dismissible fade show" role="alert">-->
<!--                    {{ message }}-->
<!--                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>-->
<!--                </div>-->
<!--                {% endfor %}-->
<!--            {% endif %}-->
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

mygametracker/user/templates/dashboard.html
<!--For experimental purposes only-->

{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}

{% if request.session.curr_user != '' %}

<table class="table table-striped table-hover table-bordered">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">Birthdate</th>
            <th scope="col">Date Joined</th>
            <th scope="col">Email</th>
            <th scope="col">Bio</th>
            <th scope="col">Gender</th>
            </tr>
    </thead>
    <tbody>
    {% if users %}
	{% for user in users %}
		<tr>
			<td>{{ user.user_id }}</td>
			<td>{{ user.username }}</td>
			<td>{{ user.birthdate }}</td>
			<td>{{ user.join_date }}</td>
			<td>{{ user.email }}</td>
			<td>{{ user.bio }}</td>
			<td>{{ user.gender }}</td>
		</tr>
	{% endfor %}
    {% endif %}
    </tbody>
</table>

{% else %}

<h1>You are not logged in.</h1>

{% endif %}

{% endblock %}

mygametracker/user/templates/friends.html
{% extends 'base.html' %}
{% block title %}Friends{% endblock %}
{% block content %}

{% if request.session.curr_user != '' %}

<h1>{{ request.session.curr_user }}'s Friends</h1>

    <br>

    <div class="card-body p-0">
        <table class="table table-dark table-hover table-borderless table-responsive my-1">
            <thead class="border-bottom">
            <tr>
                <th class="text-center">Friend Name</th>
                <th class="text-center">Date Added</th>
            </tr>
            </thead>
            <tbody>
            {% for friend in friends %}
            <tr class="position-relative align-middle">
                <td class="fs-5 text-center">{{ friend.friend_username }}</td>
                <td class="text-center">{{ friend.date_added }}</td>
                {% endfor %}
            </tbody>
        </table>

            <!-- Remove Friend modal -->
            <form method="post" action="{% url 'user:friends' %}">
                {% csrf_token %}
                <div class="modal fade" id="unfriendModal{{ friend.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h3>Remove Friend</h3>
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <input type="text" name="friend_username" class="form-control" placeholder="Enter the username of friend... (e.g. OsamaBin911)" required>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-success" name="btnConfirm" value="Confirm">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <!-- Add Friend Modal -->
            <form method="post" action="{% url 'user:add_friend' %}">
                {% csrf_token %}
                <div class="modal fade" id="addFriend">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h4>Add New Friend</h4>
                                <button type="button" class="btn-close btn-close-white"
                                        data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <input type="text" name="friend_username" class="form-control" placeholder="Enter the username of friend... (e.g. OsamaBin911)" required>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-success" name="btnAddFriend" value="Add">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
    </div>

<br>

    <div style="display: flex; justify-content: center;">
        <button type="button" class="btn btn-primary mt-2 mx-2" data-bs-toggle="modal" data-bs-target="#addFriend">Add New Friend</button>
        <button type="button" class="btn btn-danger mt-2 mx-2" data-bs-toggle="modal" data-bs-target="#unfriendModal">Unfriend</button>
    </div>

  </div>
<!--<div class="card bg-dark text-light border-light mt-3">-->
<!--  <div class="card-body">This page should contain a list of the user's friend. The user should be able to add and remove friends as well as visit their profile upon clicking.</div>-->
<!--</div>-->

{% else %}

<div class="alert alert-dismissible fade show border border-light">
  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  <strong>Info!</strong> You are currently not logged in.
</div>
<h1>Friends</h1>
<div class="card bg-dark text-light border-light mt-3">
  <div class="card-body">This page should contain a list of the user's friend. The user should be able to add and remove friends as well as visit their profile upon clicking.</div>
</div>

{% endif %}

{% endblock %}

mygametracker/user/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
    <br>
    <h1>Login</h1>
    <form method="post" action="{% url 'user:login' %}" id="login_form">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Log In">
        {% if response %}
        <p>No such username or password</p>
        {% endif %}
    </form>
{% endblock %}

mygametracker/user/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'user:dashboard' %}">MyGameTracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if request.session.curr_user != '' %}
        <li class="nav-item">
          <a class="nav-link" href="">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Forums</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
            Account
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="">Profile</a>
            <a class="dropdown-item" href="">Friends</a>
            <a class="dropdown-item" href="">Collections</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'user:logout' %}">Log Out</a>
          </div>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="">Games</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="">Forums</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown">
            Account
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'user:signup' %}">Sign Up</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'user:login' %}">Log In</a>
          </div>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>

mygametracker/user/templates/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}
{% block content %}

{% if request.session.curr_user != '' %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible fade show border border-light">
        <button class="btn-close" data-bs-dismiss="alert" type="button"></button>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}
<body>
    <script>
        const greetings = [
            "Taking a look at yourself, ",
            "Reflecting upon yourself, ",
            "Examining your own profile, ",
            "Introspecting into your details, ",
            "Observing your information, ",
            "Exploring your profile, ",
            "Delving into your details, ",
            "Peering into your profile, ",
            "Taking a closer look at you, ",
            "Reviewing your information, ",
            "Analyzing your profile, ",
            "Inspecting your details, ",
            "Exploring who you are, ",
            "Considering your profile, ",
            "Scrutinizing your information, ",
            "Observing your data, ",
        ];

        const randomIndex = Math.floor(Math.random() * greetings.length);

        document.write(`<h1 style="text-align: center">${greetings[randomIndex]}{{ request.session.curr_user }}?   </h1>`);
    </script>

    <br>

<div id="profile" class="card bg-dark text-light border-light">
    <div class="container mt-4 pb-5">
        <br>
        <form id="profileForm">
            <div class="mb-3">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" readonly value="{{ user.username }}">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Password</label>
                <div class="input-group">
                    <input type="password" class="form-control" id="password" aria-describedby="passwordToggle" readonly value="{{ user.password }}">
                    <button class="btn btn-outline-secondary" type="button" id="passwordToggle" onclick="togglePasswordVisibility()">Show</button>
                </div>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" readonly value="{{ user.email }}">
            </div>
            <div class="mb-3">
                <label for="bio" class="form-label">Bio</label>
                <textarea class="form-control" id="bio" readonly>{{ user.bio }}</textarea>
            </div>
            <div class="mb-3">
                <label for="gender" class="form-label">Gender</label>
                <input type="text" class="form-control" id="gender" readonly value="{{ user.get_gender_display }}">
            </div>
            <div class="mb-3">
                <label for="joindate" class="form-label">Join Date</label>
                <input type="text" class="form-control" id="joindate" readonly value="{{ user.join_date|date:'F d, Y P' }}">
            </div>
        </form>
        <br>
        <div style="display: flex; justify-content: center;">
            <button type="button" class="btn btn-primary mt-2 mx-2" data-bs-toggle="modal" data-bs-target="#editProfile">Edit Profile</button>
            <button type="button" class="btn btn-danger mt-2 mx-2" data-bs-toggle="modal" data-bs-target="#deleteProfile">Delete Profile</button>
        </div>
    </div>
</div>

    <script>
        function togglePasswordVisibility() {
            var passwordField = document.getElementById("password");
            var passwordToggle = document.getElementById("passwordToggle");

            if (passwordField.type === "password") {
                passwordField.type = "text";
                passwordToggle.textContent = "Hide";
            } else {
                passwordField.type = "password";
                passwordToggle.textContent = "Show";
            }
        }
    </script>

            <!-- Edit Profile Modal -->
            <form method="post" action="{% url 'user:profile' %}">
                {% csrf_token %}
                <div class="modal fade" id="editProfile">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h4>Add New Friend</h4>
                                <button type="button" class="btn-close btn-close-white"
                                        data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                    {{ form.as_p }}
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-primary" name="btnSubmit" value="Submit">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <!-- Delete Profile modal -->
            <form method="post" action="{% url 'user:delete_profile' %}">
                {% csrf_token %}
                <div class="modal fade" id="deleteProfile">
                    <div class="modal-dialog">
                        <div class="modal-content bg-dark">
                            <div class="modal-header">
                                <h4>Are you sure you want to delete </h4>
                                <button type="button" class="btn-close btn-close-white"
                                        data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-footer">
                                <input type="submit" class="btn btn-success" name="btnConfirm" value="Confirm">
                                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

</body>

<!--<h1>User's Profile</h1>-->
<!--<div class="card bg-dark text-light border-light mt-3">-->
<!--  <div class="card-body">This page should contain all the relevant information about the user. If the current user is visiting their own profile, they should have the ability to edit certain information in their profile.</div>-->
<!--</div>-->

{% else %}

<div class="alert alert-dismissible fade show border border-light">
  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  <strong>Info!</strong> You are currently not logged in.
</div>
<h1>Profile</h1>
<div class="card bg-dark text-light border-light mt-3">
  <div class="card-body">This page should contain all the relevant information about the user. If the current user is visiting their own profile, they should have the ability to edit certain information in their profile.</div>
</div>

{% endif %}

{% endblock %}

mygametracker/user/templates/signup.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock %}
{% block content %}
    <br>
    <h1>Sign Up</h1>
    <form method="post" action="{% url 'user:signup' %}" id="signup_form">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-success" value="Sign Up">
        {% if response %}
        <p>User already exists</p>
        {% endif %}
    </form>
{% endblock %}