mygametracker/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='main'),
    path('create/', views.create_forum, name='create_forum'),
    path('<int:forum_id>/', views.forum_details, name='forum_details'),
    path('<int:forum_id>/update/', views.update_forum, name='update_forum'),
    path('forums/<int:forum_id>/create_post/', views.create_post, name='create_post'),
    path('update_post/<int:post_id>/', views.UpdatePostView.as_view(), name='update_post'),
]

mygametracker/game/urls.py
from django.urls import path
from .views import home, add_new_game, top_credits, games_list

app_name = 'game'

urlpatterns = [
    path('', home, name='home'),
    path('add_new_game/', add_new_game, name='add_new_game'),
    path('top_credits/', top_credits, name='top_credits'),
    path('games_list/', games_list, name='games_list'),
]

mygametracker/mygametracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('collections/', include('collection.urls')),
    path('forum/', include('forum.urls')),
    path('', include('game.urls')),
    path('stats/', include('stats.urls')),
]

mygametracker/forum/models.py
from django.db import models
from django.utils import timezone
from user.models import User
from game.models import Game


# Create your models here.
class Forum(models.Model):
    forum_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    game = models.ManyToManyField(Game, through='GameForumRelationship')
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1) # add user that created the forum
    post_count = models.PositiveIntegerField(default=0)
    _original_title = None
    _original_description = None

    def save(self, *args, **kwargs):
        if self.pk is None:
            self._original_title = self.title
            self._original_description = self.description
        else:
            if self.title != self._original_title or self.description != self._original_description:
                self.last_updated = timezone.now()

        super().save(*args, **kwargs)

    def update_forum_stats(self):
        self.post_count = self.post_set.count()

        latest_post = self.post_set.order_by('-posted_on').first()

        if latest_post:
            self.last_updated = latest_post.posted_on
        else:
            self.last_updated = self.created_on

        if self.title != self._original_title or self.description != self._original_description:
            self.last_updated = timezone.now()

        self.save()

    def __str__(self):
        return self.title


class Post(models.Model):
    # individual posts in forums
    post_id = models.AutoField(primary_key=True)
    content = models.TextField()
    posted_on = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    _original_content = None

    def save(self, *args, **kwargs):
        if self.pk is None:
            self._original_content = self.content
        else:
            if self.content != self._original_content:
                self.last_updated = timezone.now()

        super().save(*args, **kwargs)

    def __str__(self):
        return self


class GameForumRelationship(models.Model):
    # to have a many-to-many relationship between game and forum
    # without touching the game model (not my part)
    gameforum_id = models.AutoField(primary_key=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

    def __str__(self):
        return self


class UserForumParticipation(models.Model):
    # associative model for user participation in forums
    userforum_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self

mygametracker/forum/forms.py
from django import forms
from .models import Forum, Post


class ForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ['title', 'description']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']

mygametracker/forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import View
from django.db import models
from django.db.models import Count
from django.utils import timezone
from .models import Forum, Post
from .forms import ForumForm, PostForm
from user.models import User


def index(request):
    query = request.GET.get('q')
    sort_by = request.GET.get('sort_by', 'date_created')
    forums = Forum.objects.all()

    if query:
        forums = forums.filter(user__username__icontains=query) | forums.filter(title__icontains=query) | forums.filter(description__icontains=query)

    if sort_by == 'date_created':
        forums = forums.order_by('-created_on')
    elif sort_by == 'oldest_date_created':
        forums = forums.order_by('created_on')
    elif sort_by == 'top_day':
        forums = forums.annotate(
            num_posts=Count('post', filter=models.Q(post__posted_on__gte=timezone.now() - timezone.timedelta(days=1))))
        forums = forums.order_by('-num_posts', '-created_on')
    elif sort_by == 'top_month':
        forums = forums.annotate(
            num_posts=Count('post', filter=models.Q(post__posted_on__gte=timezone.now() - timezone.timedelta(days=30))))
        forums = forums.order_by('-num_posts', '-created_on')
    elif sort_by == 'top_year':
        forums = forums.annotate(num_posts=Count('post', filter=models.Q(
            post__posted_on__gte=timezone.now() - timezone.timedelta(days=365))))
        forums = forums.order_by('-num_posts', '-created_on')
    elif sort_by == 'num_posts':
        forums = forums.annotate(num_posts=Count('post')).order_by('-num_posts', '-created_on')

    return render(request, 'forum.html', {'forums': forums, 'search_query': query, 'sort_by': sort_by})


def create_forum(request):
    if request.method == 'POST':
        form = ForumForm(request.POST)
        if form.is_valid():
            if 'curr_user' in request.session:
                forum = form.save(commit=False)
                forum.user = User.objects.get(username=request.session['curr_user'])
                forum.save()
                messages.success(request, 'Forum created successfully!')
                return redirect('forum:main')
            else:
                messages.error(request, 'You need to be logged in to create a forum.')
                return redirect('forum:main')
    else:
        form = ForumForm()

    return render(request, 'create_forum.html', {'form': form})


def forum_details(request, forum_id):
    query = request.GET.get('q')
    forum = get_object_or_404(Forum, pk=forum_id)
    posts = Post.objects.filter(forum=forum)

    sort_by = request.GET.get('sort_by', 'date_created')

    if query:
        posts = posts.filter(user__username__icontains=query) | posts.filter(content__icontains=query)

    if sort_by == 'date_created':
        posts = posts.order_by('-posted_on')
    elif sort_by == 'oldest_date_created':
        posts = posts.order_by('posted_on')

    user_is_creator = False

    if 'curr_user' in request.session:
        current_user_username = request.session['curr_user']
        current_user = User.objects.filter(username=current_user_username).first()

        if current_user and current_user == forum.user:
            user_is_creator = True

    return render(request, 'forum_details.html', {'forum': forum, 'posts': posts, 'user_is_creator': user_is_creator, 'search_query': query, 'sort_by': sort_by})


def update_forum(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)

    if request.method == 'POST':
        action = request.POST.get('action')

        if action == 'update':
            form = ForumForm(request.POST, instance=forum)
            if form.is_valid():
                form.save()
                messages.success(request, 'Forum details updated successfully!')
                forum.update_forum_stats()
                return redirect('forum:forum_details', forum_id=forum_id)
        elif action == 'delete':
            forum.delete()
            messages.success(request, 'Forum deleted successfully!')
            return redirect('forum:main')
        elif action == 'cancel':
            return redirect('forum:forum_details', forum_id=forum_id)
    else:
        form = ForumForm(instance=forum)

    return render(request, 'update_forum.html', {'forum': forum, 'form': form})


def create_post(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    if request.method == 'POST':
        form = PostForm(request.POST)

        current_user = "Anonymous"
        if 'curr_user' in request.session:
            current_user_username = request.session['curr_user']
            current_user = User.objects.filter(username=current_user_username).first()

        if form.is_valid():
            post = form.save(commit=False)
            post.forum = forum
            post.user = current_user
            post.save()

            forum.update_forum_stats()

            return redirect('forum:forum_details', forum_id=forum_id)
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form, 'forum': forum})


class UpdatePostView(View):
    template_name = 'update_post.html'

    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        form = PostForm(instance=post)
        return render(request, self.template_name, {'form': form, 'post': post})

    def post(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        form = PostForm(request.POST, instance=post)
        action = request.POST.get('action')

        if action == 'delete_post':
            forum = get_object_or_404(Forum, pk=post.forum_id)
            post.delete()
            messages.success(request, 'Post deleted successfully.')
            forum.update_forum_stats()
            return redirect('forum:forum_details', forum_id=post.forum.pk)

        if form.is_valid():
            form.save()
            messages.success(request, 'Post updated successfully.')
            return redirect('forum:forum_details', forum_id=post.forum.pk)

        return render(request, self.template_name, {'form': form, 'post': post})

mygametracker/forum/templates/create_forum.html
{% extends 'base.html' %}
{% block title %}Create Forum{% endblock %}
{% block content %}
<form method="post" action="{% url 'forum:create_forum' %}">
    {% csrf_token %}
    {{ form.title.errors }}
    {{ form.title.label_tag }} {{ form.title }}<br><br>

    {{ form.description.errors }}
    {{ form.description.label_tag }}<br>{{ form.description }}<br>
    <button type="submit" class="btn btn-secondary">Create Forum</button>
    <a href="{% url 'forum:main' %}" class="btn btn-primary">Cancel</a>
</form>

{% endblock %}

mygametracker/forum/templates/create_post.html
{% extends 'base.html' %}
{% block title %}Create Post{% endblock %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.content.errors }}
    {{ form.content.label_tag }}<br>{{ form.content }}<br>
    <input type="submit" value="Create Post" class="btn btn-success">
    <a href="{% url 'forum:forum_details' forum_id=forum.pk %}" class="btn btn-danger">Cancel</a>
</form>

{% endblock %}

mygametracker/forum/templates/forum.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Forum{% endblock %}
{% block content %}

<h1>Forum</h1>

{% if request.session.curr_user == '' %}
      <div class="alert alert-dismissible fade show border border-light">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <strong>Info!</strong> You are currently not logged in.
      </div>
{% endif %}


<div class="d-flex justify-content-between mt-3">
    <div>
        <form method="get" action="{% url 'forum:main' %}">
            <select id="sort-by" name="sort_by" class="form-select" onchange="this.form.submit()">
                <option value="" selected disabled>Sort by</option>
                <optgroup label="Date Created">
                    <option value="date_created" {% if sort_by == 'date_created' %}selected{% endif %}>Latest</option>
                    <option value="oldest_date_created" {% if sort_by == 'oldest_date_created' %}selected{% endif %}>Oldest</option>
                </optgroup>
                <optgroup label="Top Posts">
                    <option value="top_day" {% if sort_by == 'top_day' %}selected{% endif %}>Day</option>
                    <option value="top_month" {% if sort_by == 'top_month' %}selected{% endif %}>Month</option>
                    <option value="top_year" {% if sort_by == 'top_year' %}selected{% endif %}>Year</option>
                </optgroup>
                <optgroup label="Number of Posts">
                    <option value="num_posts" {% if sort_by == 'num_posts' %}selected{% endif %}>Number of Posts</option>
                </optgroup>
            </select>
            <input type="hidden" name="q" value="{% if search_query %}{{ search_query }}{% endif %}">
        </form>
    </div>

    <div class="flex-grow-1 mx-2">
        <form method="get" action="{% url 'forum:main' %}">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search forum creator, title, or description" name="q" value="{% if search_query %}{{ search_query }}{% endif %}">
                <button class="btn btn-secondary" type="submit">Search</button>
            </div>
        </form>
    </div>

    <div>
        {% if request.session.curr_user != '' %}
            <a href="{% url 'forum:create_forum' %}" class="btn btn-success">Create New Forum</a>
        {% endif %}
    </div>
</div>

<div class="card bg-dark text-light border-light mt-3">
  <div class="card-body">
    {% if forums %}
      <ul class="list-group forum-list">
        {% for forum in forums %}
            <a href="{% url 'forum:forum_details' forum_id=forum.pk %}" class="text-decoration-none text-light">
                <li class="list-group-item {% if forloop.last %}border-bottom-0{% endif %} border-top-0 border-start-0 border-end-0 bg-dark text-light">
                    <div class="d-flex justify-content-between align-items-start">
                        <h4 class="mb-0">
                          {{ forum.title }}
                        </h4>
                        <p class="mb-1 small text-secondary">
                            Created by {{ forum.user.username }}
                            <span data-toggle="tooltip" title="{{ forum.created_on|date:'D, F d, Y, h:i A' }}">
                                {{ forum.created_on|simplify_timesince }} ago
                            </span>
                            • <span class="text-light">Posts: {{ forum.post_count }}</span>
                        </p>
                  </div>
                  <p class="mb-1">{{ forum.description }}</p>
                </li>
            {% endfor %}
          </a>
      </ul>
    {% else %}
      <p>No forums available.</p>
    {% endif %}
  </div>
</div>

{% endblock %}

mygametracker/forum/templates/forum_details.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block title %}Forum Details{% endblock %}
{% block content %}

<div class="row">
    <div class="col-md-8">
        <h1>{{ forum.title }}</h1>

        <p class="small">Created by {{ forum.user.username }} on {{ forum.created_on|date:'D, F d, Y, h:i A' }}
            <span class="text-secondary">
                • Last updated on {{ forum.last_updated|date:'D, F d, Y, h:i A' }}
            </span>
        </p>
        <p>Number of posts: {{ forum.post_count }}</p>
        <p>Description: {{ forum.description }}</p>
    </div>

    <div class="col-md-4">
        {% if request.session.curr_user != '' %}
            {% if user_is_creator %}
                <a href="{% url 'forum:update_forum' forum_id=forum.pk %}" class="btn btn-success">Update Forum</a>
            {% endif %}
        {% endif %}
    </div>
</div>

<div class="row">
    <div class="col-md-9">
        <div class="d-flex justify-content-between">
            <div>
                <h2>Posts</h2>
            </div>

            <div class="d-flex align-items-center">
                <form method="get" action="{% url 'forum:forum_details' forum_id=forum.pk%}" class="me-2">
                    <select id="sort-by" name="sort_by" class="form-select" onchange="this.form.submit()">
                        <option value="" selected disabled>Sort by</option>
                        <option value="date_created" {% if sort_by == 'date_created' %}selected{% endif %}>Latest</option>
                        <option value="oldest_date_created" {% if sort_by == 'oldest_date_created' %}selected{% endif %}>Oldest</option>
                    </select>
                    <input type="hidden" name="q" value="{% if search_query %}{{ search_query }}{% endif %}">
                </form>

                <form method="get" action="{% url 'forum:forum_details' forum_id=forum.pk%}" class="me-2">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search post or author" name="q" value="{% if search_query %}{{ search_query }}{% endif %}">
                        <input type="hidden" name="sort_by" value="{% if sort_by %}{{ sort_by }}{% endif %}">
                        <button class="btn btn-secondary" type="submit">Search</button>
                    </div>
                </form>

                {% if request.session.curr_user != '' %}
                    <a href="{% url 'forum:create_post' forum_id=forum.pk %}" class="btn btn-success">Create Post</a>
                {% endif %}
            </div>
        </div>

        {% if posts %}
            <ul class="list-group forum-list">
                {% for post in posts %}
                    <li class="list-group-item {% if forloop.last %}border-bottom-0{% endif %} border-top-0 border-start-0 border-end-0 bg-dark text-light">
                        <div class="d-flex align-items-center">
                            <div class="border-end small" style="width: 150px; padding-right: 15px">
                                <p><strong>Posted by {{ post.user.username }}</strong><br>
                                    <span class="small" data-toggle="tooltip" title="{{ post.posted_on|date:'D, F d, Y, h:i A' }}">{{ post.posted_on|simplify_timesince }} ago</span>
                                    {% if post.posted_on != post.last_updated %}
                                        • <span class="small" data-toggle="tooltip" title="{{ post.last_updated|date:'D, F d, Y, h:i A' }}">Edited</span>
                                    {% endif %}
                                </p>
                                {% if request.session.curr_user == post.user.username %}
                                    <p class="small"><a href="{% url 'forum:update_post' post_id=post.pk %}">Update Post</a></p>
                                {% endif %}
                            </div>
                            <div class="align-items-center" style="padding-left: 1rem">
                                <p class="mb-0">{{ post.content }}</p>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No posts available.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

mygametracker/forum/templates/update_forum.html
{% extends 'base.html' %}
{% block title %}Update Forum{% endblock %}
{% block content %}

<h1>Update Forum</h1>

<form method="post" action="{% url 'forum:update_forum' forum_id=forum.pk %}">
    {% csrf_token %}
    {{ form.title.errors }}
    {{ form.title.label_tag }} {{ form.title }}<br><br>

    {{ form.description.errors }}
    {{ form.description.label_tag }}<br>{{ form.description }}<br>
    <button type="submit" name="action" value="update" class="btn btn-success">Update Forum Details</button>
    <button type="submit" name="action" value="delete" class="btn btn-danger">Delete Forum</button>
    <a href="{% url 'forum:forum_details' forum_id=forum.pk %}" class="btn btn-secondary">Cancel</a>
</form>

{% endblock %}

mygametracker/forum/templates/update_post.html
{% extends 'base.html' %}
{% block title %}Update Post{% endblock %}
{% block content %}
<h1>Update Post</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.content.errors }}
    {{ form.content.label_tag }}<br>{{ form.content }}<br>
    <button type="submit" class="btn btn-success">Update Post</button>
    <button type="submit" name="action" value="delete_post" class="btn btn-danger">Delete Post</button>
    <a href="{% url 'forum:forum_details' forum_id=post.forum.pk %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}